name: Publish docs

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.4.0
        with:
          submodules: 'true'

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.x'

      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: github-action
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.tools.sap"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy